STORES = {
    "chipotle": "Eating Out",
    "quesada" : "Eating Out",
    "starbucks": "Eating Out",
    "spotify": "Disgressionary",
    "digital ocean": "Disgressionary",
    "real canadian superstore": "Groceries",
    "amazon": "Disgressionary",
    "raw source": "Pets",
    "quiznos": "Eating Out",
    "oakridge animal clinic": "Pets",
    "nando": "Eating Out",
    "rona": "home",
    "petro": "Gas",
    "koodo mobile": "Disgressionary",
    "paypal": "Disgressionary",
    "aliexpress": "Disgressionary",
    "pizza hut": "Eating Out",
    "kfc": "Eating Out",
    "the bungalow": "Eating Out",
    "bell canada": "Entertainment",
    "netflix": "Entertainment",
    "five guys burgers": "Eating Out",
    "london bridge child": "Child Care",
    "shell": "Gas",
    "swiss chalet": "Eating Out",
    "shoppers drug mart": "Groceries",
    "wendy": "Eating Out",
    "metro": "Groceries",
    "domino": "Eating Out",
    "popeye's lousiana": "Eating Out"
}

VENMOS = {
    "food": "Eating Out",
    "tickets": "Disgressionary",
    "internet": "Rent & Utilities",
}
